### ISSUE TITLE
RuntimeError: Unsupported statement 'Try'.

### ISSUE THREAD

**Issue by xiaoma-ustc** [zhanghuiyao/yolov7_mindspore#1]
Traceback (most recent call last):
  File "train.py", line 808, in <module>
    train(hyp, opt)
  File "train.py", line 236, in train
    _, loss_item, grads, grads_finite = train_step(imgs, labels, ns, True)
  File "/root/miniconda3/lib/python3.8/site-packages/mindspore/common/api.py", line 559, in staging_specialize
    out = _MindsporeFunctionExecutor(func, hash_obj, input_signature, process_obj, jit_config)(*args)
  File "/root/miniconda3/lib/python3.8/site-packages/mindspore/common/api.py", line 98, in wrapper
    results = fn(*arg, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/mindspore/common/api.py", line 360, in __call__
    phase = self.compile(args_list, self.fn.__name__)
  File "/root/miniconda3/lib/python3.8/site-packages/mindspore/common/api.py", line 323, in compile
    is_compile = self._graph_executor.compile(self.fn, compile_args, phase, True)
RuntimeError: Unsupported statement 'Try'.

**Comment by xiaoma-ustc** [comment]
----------------------------------------------------
- The Traceback of Net Construct Code:
----------------------------------------------------

# In file /root/miniconda3/lib/python3.8/site-packages/mindspore/context.py(412)
        try:

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/jit/parse/parse.cc:725 ParseStatement

**Comment by xiaoma-ustc** [comment]
The Traceback of Net Construct Code:


#In file /root/miniconda3/lib/python3.8/site-packages/mindspore/context.py(412)
   try:


 C++ Call Stack: (For framework developers)

mindspore/ccsrc/pipeline/jit/parse/parse.cc:725 ParseStatement

**Comment by zhanghuiyao** [comment]
This problem has been fixed in the later MindSpore version. You can try version 1.9.0

**Comment by xiaoma-ustc** [comment]
Thank You!
