### ISSUE TITLE
How to start training?

### ISSUE THREAD

**Issue by xiaoma-ustc** [zhanghuiyao/yolov7_mindspore#2]
I had tried MindSpore1.9.0, but when I use 
```
python train.py --workers 8 --device 0 --batch-size 32 --data data/coco.yaml --img 640 640 --cfg config/network_yolov7/yolov7.yaml --weights '' --name yolov7 --hyp config/data/hyp.scratch.p5.yaml
```
it keeps showing me the following error: 
```
[WARNING] ME(50567:139952706982592,MainProcess):2022-11-26-21:52:27.165.094 [mindspore/ops/primitive.py:710] The "use_copy_slice" is a constexpr function. The input arguments must be all constant value.
[WARNING] ME(50567:139952706982592,MainProcess):2022-11-26-21:52:27.195.190 [mindspore/ops/primitive.py:710] The "is_slice" is a constexpr function. The input arguments must be all constant value.
[WARNING] ME(50567:139952706982592,MainProcess):2022-11-26-21:52:29.534.109 [mindspore/ops/primitive.py:710] The "use_copy_slice" is a constexpr function. The input arguments must be all constant value.
[WARNING] MD(50567,7f439dc28700,python):2022-11-26-21:54:53.177.486 [mindspore/ccsrc/minddata/dataset/engine/datasetops/source/generator_op.cc:195] operator()] Bad performance attention, it takes more than 25 seconds to generator.__next__ new row, which might cause `GetNext` timeout problem when sink_mode=True. You can increase the parameter num_parallel_workers in GeneratorDataset / optimize the efficiency of obtaining samples in the user-defined generator function.
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.767.203 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:255] CalMemBlockAllocSize] Memory not enough: current free memory size[41484288] is smaller than required size[3538944000].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.767.240 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:544] DumpDynamicMemPoolDebugInfo] Start dump dynamic memory pool debug info.
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.767.254 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:503] operator()] Common mem all mem_block info: counts[10].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.767.267 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:507] operator()]  MemBlock info: number[0] mem_buf_counts[3] base_address[0x7f3e08000000] block_size[4133221120].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.767.280 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:507] operator()]  MemBlock info: number[1] mem_buf_counts[1] base_address[0x7f3f00000000] block_size[1073741824].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.767.291 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:507] operator()]  MemBlock info: number[2] mem_buf_counts[2] base_address[0x7f3f40000000] block_size[1073741824].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.767.302 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:507] operator()]  MemBlock info: number[3] mem_buf_counts[3] base_address[0x7f3f80000000] block_size[1073741824].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.767.315 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:507] operator()]  MemBlock info: number[4] mem_buf_counts[4] base_address[0x7f3fc8000000] block_size[2147483648].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.767.335 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:507] operator()]  MemBlock info: number[5] mem_buf_counts[31] base_address[0x7f4048000000] block_size[2147483648].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.767.354 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:507] operator()]  MemBlock info: number[6] mem_buf_counts[16] base_address[0x7f40c8000000] block_size[1073741824].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.767.367 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:507] operator()]  MemBlock info: number[7] mem_buf_counts[2] base_address[0x7f4108000000] block_size[1073741824].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.767.385 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:507] operator()]  MemBlock info: number[8] mem_buf_counts[32] base_address[0x7f4148000000] block_size[4294967296].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.767.531 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:507] operator()]  MemBlock info: number[9] mem_buf_counts[282] base_address[0x7f4432000000] block_size[1073741824].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.767.562 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:524] operator()] Common mem all idle mem_buf info: counts[46].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.767.578 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:534] operator()] Common mem total allocated memory[19165606656], used memory[16271860224], idle memory[2893746432].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.767.589 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:503] operator()] Persistent mem all mem_block info: counts[1].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.767.931 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:507] operator()]  MemBlock info: number[0] mem_buf_counts[1116] base_address[0x7f43e6000000] block_size[1073741824].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.768.015 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:524] operator()] Persistent mem all idle mem_buf info: counts[1].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.768.027 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:534] operator()] Persistent mem total allocated memory[1073741824], used memory[558091264], idle memory[515650560].
[WARNING] PRE_ACT(50567,7f44dd7fa700,python):2022-11-26-21:54:53.768.038 [mindspore/ccsrc/common/mem_reuse/mem_dynamic_allocator.cc:547] DumpDynamicMemPoolDebugInfo] Finish dump dynamic memory pool debug info.
Traceback (most recent call last):
  File "train.py", line 807, in <module>
    train(hyp, opt)
  File "train.py", line 235, in train
    _, loss_item, _, grads_finite = train_step(imgs, labels, ns, True)
  File "/root/miniconda3/lib/python3.8/site-packages/mindspore/common/api.py", line 594, in staging_specialize
    out = _MindsporeFunctionExecutor(func, hash_obj, input_signature, process_obj, jit_config)(*args)
  File "/root/miniconda3/lib/python3.8/site-packages/mindspore/common/api.py", line 98, in wrapper
    results = fn(*arg, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/mindspore/common/api.py", line 409, in __call__
    output = self._graph_executor(tuple(new_inputs), phase)
RuntimeError: Device(id:0) memory isn't enough and alloc failed, kernel name: Default/Sub-op11531, alloc size: 3538944000B.

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/runtime/graph_scheduler/graph_scheduler.cc:632 Run
```

***So how can I do to start training? Is there a Quich Start order?***

I'm a beginner in MindSpore, thank you for your help.

**Comment by zhanghuiyao** [comment]
You can try running the following command on the gpu
"""
cd scripts
bash run_ distribute_ train_ gpu.sh

or 

python train.py \
  --ms_strategy="StaticShape"
  --ms_amp_level="O0" \
  --ms_loss_scaler="static" \
  --ms_loss_scaler_value=1024 \
  --ms_optim_loss_scale=1024 \
  --ms_grad_sens=1024 \
  --overflow_still_update=False \
  --clip_grad=False \
  --device_target=GPU \
  --is_distributed=True \
  --epochs=300 \
  --batch-size=16
"""

**Comment by xiaoma-ustc** [comment]
OK, I found I used too large batch_size.
Thank you again!
